### ISSUE TITLE
Feature Request: Razor Language

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/monaco-languages#1]
Is there any chance there is upcoming support for the C# MVC template language Razor for .cshtml files?

**Comment by egamma** [comment]
A discussion on Razor support has been started here: https://github.com/OmniSharp/omnisharp-vscode/issues/168

**Comment by warrenbuckley** [comment]
@egamma I noticed that on the Monaco Demo site the Razor language is in the dropdown https://microsoft.github.io/monaco-editor/index.html

**Comment by egamma** [comment]
@warrenbuckley correct, but this is colorizing only. I thought you asked for deep language support, that is go to definition, intellisense, etc.

**Comment by warrenbuckley** [comment]
@egamma of course deeper language support would be fantastic but colourisation is a great start. 

Will keep this open then for in regard to deeper language support.

**Comment by basarat** [comment]
> Will keep this open then for in regard to deeper language support.

FWIW that deeper integration requires non browser backend support (specifically .net). Unlikely to happen in `monaco-editor` which is web only :rose:

**Comment by egamma** [comment]
@basarat  is correct, we have no plans to re-implement a C#, Razor language in TypeScript. If you want deeper support than you can connect the editor to a backend service. This is out of the scope of the Monaco editor - closing this issue.
