### ISSUE TITLE
Rust language support

### ISSUE THREAD

**Issue by miqid** [Microsoft/monaco-languages#3]
Howdy.

Is somebody working on providing basic support for [Rust][1] as a language option for the Monaco Editor? If not, I'm willing to throw my hat into the ring to give it a shot.

I've previously authored a Rust grammar package for the Atom editor, which is based on a TextMate-like system. However, it seems like the parser used to provide syntax highlighting for the Monaco Editor is more versatile.

[1]: https://www.rust-lang.org/

**Comment by egamma** [comment]
I'm not aware of anybody building a colorzer for Rust. Here is the playground to get started with a colorizer https://microsoft.github.io/monaco-editor/monarch.html

**Comment by jrieken** [comment]
This issue was moved to Microsoft/monaco-editor#130
