### ISSUE TITLE
Add support for tmbundle for shellscript

### ISSUE THREAD

**Issue by rgl** [Microsoft/monaco-languages#8]
I would like to have shellscript syntax highlight like the regular vscode editor; vscode seems to be using the tmbundle from https://github.com/textmate/shellscript.tmbundle. Can we have tmbundle support on monaco too? If you can guide me, maybe I can help port it.

**Comment by alexandrudima** [comment]
TextMate grammars are supported in vscode through the use of the `node-oniguruma` npm module (which is a native node module that exports the `oniguruma` regular expression library to JS). This is unfortunately not possible in a browser -- we tried it once with emscripten, but the perf was horrible. Maybe once all major browsers support WebAssembly we can look again into supporting TextMate grammars in the monaco editor (that runs in web browsers)
